title: 3rd Ltd.
description: The Press | Design Objects & Systems
url: "https://petersalvato.github.io/3rd-ltd-constellation"
baseurl: "/3rd-ltd-constellation"

markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Snipcart configuration
snipcart_api_key: "YOUR_PUBLIC_API_KEY_HERE"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
